In [163]:
import numpy as np

# Total Unimodularity

To determine if a Polyhedron even has an integral vertex, i.e. the corresponding linear program has an integral solution, we can use the concepts of <b>unimodularity</b> and <b>dual integrality<b>.

A matrix $A \in Z^{m \times n}$ is called <b>unimodular</b> if every $(m \times m)$ submatrix has determinant -1, 1 or 0.
It is called <b>totally unimodular (TU)</b> if the determinant of <i>every</i> submatrix has determinant -1, 1 or 0.

While every TU matrix with full row rank is unimodular, the opposite does not hold, as the following example shows:

In [164]:
A = np.matrix('2 3 2; 4 2 3; 9 6 7')
A

matrix([[2, 3, 2],
        [4, 2, 3],
        [9, 6, 7]])

The determinant of this Matrix, which is it's only $(3 \times 3)$ submatrix, is 1.

In [165]:
np.linalg.det(A)

1.0000000000000102

But not the determinant of every submatrix, which would include single cells, that are not all -1, 1 or 0.

Important relations of a matrix $A \in Z^{m \times n}$ with full row rank and polyhedra induced by it, are the following:<br><br>
* $A$ is TU $\iff P := \{x|Ax=b, x\geq 0\}$ is integral $\forall b\in Z^m$<br>
* $A$ is TU $\iff P := \{x|Ax\leq b, x\geq 0\}$ is integral $\forall b\in Z^m$<br>
* $A$ is TU  $\Rightarrow P := \{x|Ax=b, x\geq 0\}$ is integral $\forall b\in Z^m$

# Dual Integrality

Using the above, we can directly derive an important insight into the existance of integer solutions of the primal and dual version of an LP:<br><br>
If $A$ is TU and $b, c$ are integral $\Rightarrow$ $max\{c^Tx|Ax\leq b\}=min\{b^Ty|A^Ty=c, y\geq0\}$ both have integral optimal solutions if they are feasible & bounded.

# Hermite Normal Form

For the remainder, we need another concept, which is the <b>Hermite Normal Form (HNF).</b><br><br>
A matrix $A$ is in HNF, if it has the form $A=[B,0]$, where $B$ is a non-negative lower triangular matrix and $B$ has the unique maximum entry of each row on the diagonal.<br><br>
Every rational matrix $A \in Q^{m \times n}$ of full row rank can be brought into HNF with <b>unimodular column operations</b> which are:
* Swapping the columns of A
* Negating colums of A
* Adding a multiple of a column of A onto another column

The column operations can be expressed as multiplications with unimodular matrices, which can be combined in a (unimodular) matrix $U$, such that $AU = [B,0]$. The matrices $B$ and $U$ are uniqe and can be computed in polytime.
<br><br>
For $x \in R^5$, the operations would look like this in matrix form:

In [166]:
# Swapping indices i and j
i = 1
j = 2
swapping_operation = np.eye(5)
swapping_operation[i, i] = 0
swapping_operation[j, j] = 0
swapping_operation[i, j] = swapping_operation[j, i] = 1
swapping_operation

array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [167]:
# Negating index j=2
j = 2
negate_operation = np.eye(5)
negate_operation[j,j] *= -1
negate_operation

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [168]:
# Adding multiples (k) of index j to index i
k = 3
j = 2
i = 1
adding_operation = np.eye(5)
adding_operation[j, i] = k
adding_operation

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 3., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Let's look at an example:

In [169]:
A = np.matrix('4 8 0 -4 4; 3 -6 6 9 0; 2 -2 0 4 -4')
A

matrix([[ 4,  8,  0, -4,  4],
        [ 3, -6,  6,  9,  0],
        [ 2, -2,  0,  4, -4]])

First, we can substract the first column two times from the second column, once from the last column and add it once to the 4th column:

In [170]:
A[:, 1] -= 2 * A[:, 0]
A[:, 3] += A[:, 0]
A[:, 4] -= A[:, 0]
A

matrix([[  4,   0,   0,   0,   0],
        [  3, -12,   6,  12,  -3],
        [  2,  -6,   0,   6,  -6]])

Then we negate the last column:

In [171]:
A[:, 4] *= -1
A

matrix([[  4,   0,   0,   0,   0],
        [  3, -12,   6,  12,   3],
        [  2,  -6,   0,   6,   6]])

Now we add the last column four times onto the second one, substract it two times from the third one and add the second column once to the fourth column:

In [172]:
A[:, 3] += A[:, 1]
A[:, 1] += 4 * A[:, 4]
A[:, 2] -= 3 * A[:, 4]
A

matrix([[  4,   0,   0,   0,   0],
        [  3,   0,  -3,   0,   3],
        [  2,  18, -18,   0,   6]])

Then we can substract column 3 from column 4, and substract column 2 from column 5:

In [173]:
A[:, 3] -= A[:, 2]
A[:, 4] -= A[:, 1]
A

matrix([[  4,   0,   0,   0,   0],
        [  3,   0,  -3,   3,   3],
        [  2,  18, -18,  18, -12]])

After that we can  substract column 2 two times from column 3 and swap it, and substract column 2 from column 1:

In [174]:
A[:, 0] -= A[:, 1]
A[:, 2] -= 2 * A[:, 3]
v = A[:, 3].copy()
A[:, 3] = A[:, 2]
A[:, 2] = v
A

matrix([[  4,   0,   0,   0,   0],
        [  3,   0,   3,  -9,   3],
        [-16,  18,  18, -54, -12]])

Finally, we arrive at our HNF $[B, 0]$, by adding column 3 onto column 1 and substracting it from column 2:

In [175]:
A[:, 0] += A[:, 2]
A[:, 1] -= A[:, 2]
A

matrix([[  4,   0,   0,   0,   0],
        [  6,  -3,   3,  -9,   3],
        [  2,   0,  18, -54, -12]])

# Integral Farkas Lemma

The HNF can be used to prove an integral version of the farkas lemma, which gives:<br><br>
Let $A \in Q^{m \times n}$, $b \in Q^m$. Then either,
<br><br>
$\exists x \in Z^n: Ax=b$ or
<br><br>
$\exists y \in Q^m: y^T A \in Z^n, y^T b \notin Z$<br><br>

For $A \in Q^{m \times n}$, $b \in Q^m$ we can use these results to obtain an integral solution $x \in Z^n$ for $Ax=b$ in polytime, or infer that no such solution exists.
<br><br>
Note that these results only hold for the equality $Ax=b$.
<br><br>
As soon as we constrain $x$ further, e.g. $x \in \{0,1\}^{m \times n}$, or want to solve $Ax\leq b$, they do not hold anymore.

# Total Dual Integrality

The integral Farkas lemma above provides enough power for the concept of total dual integrality to work.
<br><br>
For $A \in Q^{m \times n}$, $b \in Q^m$, the system $Ax\leq b$ is <b>totally dual integral (TDI)</b>, if
<br><br>
$\forall c \in Z^n: min\{b^Ty|A^Ty=c, y\geq 0\}$ has an integral solution if any exists.

Combining the concepts from above, we get two important results:
1. If $A$ is TU $\Rightarrow$ $Ax\leq b$ is TDI $\forall b \in Q^m$ <br>
2. If the system $Ax\leq b$ is TDI and $b \in Z^m$ $\Rightarrow$ $P=P(A,b)$ is integral

# Hilbert Bases

To keep going, we need to define an important property of polyhedra that are induces by TDI systems.
<br><br>
Namely, a finite subset $H=\{h^1, h^2, ..., h^t\} \subset C$ of a rational polyhedral cone $C \subset R^n$ is called a <b> Hilbert basis</b> of $C$, if 
<br><br>
$\forall z \in C \cap Z^n$ there is a $\lambda \in Z^t_{\geq 0}: z = \sum_{i=1}^t \lambda_i k^i$.
<br><br>
The Hilbert basis is called <b>integral</b> if $H \subseteq Z^n$.

Let's look at an example again:

In [ ]:
# TODO

We can derive the following connection to systems that are TDI:
<br><br>
Let $A \in Q^{m \times n}$, $b \in Q^m$ with $P=P(A,b)\neq0$.
<br><br>
If $Ax\leq b$ is TDI $\iff \forall$ (min) faces $F$ of $P$: the rows of $A_{eq(F)\bullet}$ form a Hilbert basis of cone($(A_{eq(F))\bullet})^T$).
<br><br>
This means that every rational polyhedron $P$ can be described by a TDI system $Ax\leq b$ with integral $A$!
<br><br>
And in particular:
<br><br>
If a rational polyhedron $P$ is integral $\iff$ $\exists$ a TDI system $Ax\leq b$ describing it with $A,b$ integral!
<br><br>
But still, even deciding whether a system $Ax\leq 1$ is TDI, is NP-complete.